# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=50)),
                ('domain_lead', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment_name', models.CharField(max_length=50)),
                ('is_environment_life', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
                ('service_owner', models.EmailField(max_length=100)),
                ('service_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssl_monitoring.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_fqdn', models.CharField(max_length=200)),
                ('url_environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssl_monitoring.Environment')),
            ],
        ),
        migrations.AddField(
            model_name='environment',
            name='environment_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssl_monitoring.Service'),
        ),
    ]
