# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(max_length=100)),
                ('contact_services', models.ManyToManyField(to='ssl_monitoring.Service')),
            ],
        ),
        migrations.CreateModel(
            name='UrlCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_status', models.CharField(choices=[('SHA1', 'Certificate is SHA-1 Certificate'), ('EXP', 'Certificate is Expired'), ('NR', 'URL is not Reachable'), ('VLD', 'Certificate is Valid'), ('WRN', 'Certificate is about to expire')], max_length=5)),
                ('check_date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='url',
            name='url_current_status',
            field=models.CharField(choices=[('SHA1', 'Certificate is SHA-1 Certificate'), ('EXP', 'Certificate is Expired'), ('NR', 'URL is not Reachable'), ('VLD', 'Certificate is Valid'), ('WRN', 'Certificate is about to expire')], default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urlcheck',
            name='url_reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssl_monitoring.Url'),
        ),
    ]
