# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_monitoring', '0002_auto_20170309_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='url_last_update',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
