# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_monitoring', '0003_url_url_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url_last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
