# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='url_last_update',
        ),
        migrations.AddField(
            model_name='environment',
            name='environment_server_hostname',
            field=models.CharField(default='localhost', max_length=50),
        ),
        migrations.AddField(
            model_name='environment',
            name='environment_server_user',
            field=models.CharField(default='weloadm', max_length=30),
        ),
        migrations.AddField(
            model_name='service',
            name='service_alert_setting',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='service',
            name='service_warning_setting',
            field=models.IntegerField(default=80),
        ),
    ]
