# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_monitoring', '0002_remove_url_url_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url_current_status',
            field=models.CharField(blank=True, choices=[('SHA1', 'Certificate is SHA-1'), ('EXP', 'Certificate is Expired'), ('NR', 'URL is not Reachable'), ('VLD', 'Certificate is Valid'), ('WRN', 'Certificate is about to expire')], max_length=5),
        ),
        migrations.AlterField(
            model_name='urlcheck',
            name='url_status',
            field=models.CharField(choices=[('SHA1', 'Certificate is SHA-1'), ('EXP', 'Certificate is Expired'), ('NR', 'URL is not Reachable'), ('VLD', 'Certificate is Valid'), ('WRN', 'Certificate is about to expire')], max_length=5),
        ),
    ]
